export const EVENT_NPC_DIED = "EVENT_NPC_DIED";
export const EVENT_PLAYER_HIT_NPC = "EVENT_PLAYER_HIT_NPC";
export const EVENT_TICK = "EVENT_TICK";
export const EVENT_PLAYER_LEVEL_UP = "EVENT_PLAYER_LEVEL_UP";
export const EVENT_NPC_RECEIVE_DAMAGE = "EVENT_NPC_RECEIVE_DAMAGE"
